### ISSUE TITLE
Improving the documentation of \TikzEveryCell

### ISSUE THREAD

**Issue by Basmah1961** [fpantigny/nicematrix#4]
The documentation must 

1. clearly specify the general syntax is `\TikzEveryCell[options]{TikZ keys}`
2. mention that keys `empty` and `non-empty` in the manual as optional arguments (not with `TikZ keys`)

Also, for the sake of completeness, a new key (`all`) should be be added which specifies that `\TikzEveryCell` is applied to all cells

**Comment by fpantigny** [comment]
I have modified the documentation concerning `\TikzEveryCell` and I have added an example.
